let xvondActionEditor={companyId:null,agentId:null,templateId:null,actions:[],templates:[],integrations:[],requests:[]};

function deepClone(v){return JSON.parse(JSON.stringify(v))}
function actionFieldsText(fields){return (fields||[]).map(x=>typeof x==='string'?x:(x.key||x.name||'')).filter(Boolean).join(', ')}
function actionFieldsFromText(value){return String(value||'').split(',').map(x=>x.trim()).filter(Boolean).map(key=>({key,label:key.replaceAll('_',' '),type:'text',role:(key==='date'||key.endsWith('_date'))?'date':(key==='time'||key.endsWith('_time'))?'time':'',required:true}))}
function integrationOptions(selected){return `<option value="">Select integration</option>`+xvondActionEditor.integrations.filter(x=>x.enabled&&x.configured).map(x=>`<option value="${x.id}" ${String(x.id)===String(selected||'')?'selected':''}>${f(x.name)} · ${f(x.integration_type)}</option>`).join('')}
function destinationOptions(selected){return `<option value="xvond_internal" ${selected==='xvond_internal'?'selected':''}>Xvond Dashboard — save internally</option><option value="human_handoff" ${selected==='human_handoff'?'selected':''}>Human Queue — collect then hand off</option><option value="integration" ${selected==='integration'?'selected':''}>Connected Integration — execute externally</option><option value="unconfigured" ${selected==='unconfigured'?'selected':''}>Not configured</option>`}
function availabilityOptions(selected){return `<option value="none" ${selected==='none'?'selected':''}>No availability check</option><option value="xvond_schedule" ${selected==='xvond_schedule'?'selected':''}>Xvond Schedule</option><option value="integration" ${selected==='integration'?'selected':''}>Use connected integration</option>`}
function weekdayChecks(index,weekdays){const labels=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];const set=new Set((weekdays||[]).map(Number));return labels.map((label,i)=>`<label style="margin-right:8px"><input type="checkbox" class="aa-weekday" data-index="${index}" value="${i}" ${set.has(i)?'checked':''}> ${label}</label>`).join('')}
function requestDetailsHtml(d){return Object.entries(d||{}).filter(([k])=>!k.startsWith('_')).map(([k,v])=>`<div class="meta"><strong>${f(k.replaceAll('_',' '))}:</strong> ${f(typeof v==='object'?JSON.stringify(v):v)}</div>`).join('')}
function readinessHtml(action){const issues=action.readiness_issues||[];return issues.length?`<div style="margin-top:8px;padding:8px;border:1px solid #f1c40f;border-radius:8px"><strong>Needs configuration</strong>${issues.map(x=>`<div class="meta">• ${f(x)}</div>`).join('')}</div>`:`<div class="meta" style="margin-top:8px">Ready for real execution</div>`}

function actionCard(action,index){const availability=action.availability||{mode:'none'},schedule=availability.schedule||{},destination=action.destination||{type:'unconfigured'};return `<div class="agent-card" style="margin:12px 0" data-aa-card="${index}">
<div style="display:flex;justify-content:space-between;gap:12px"><div><strong>${f(action.label||action.key||'Action')}</strong><div class="meta">${f(action.key||'')}</div></div><button class="table-button" onclick="removeAgentAction(${index})">Remove</button></div>
<div class="form-group"><label><input id="aa-enabled-${index}" type="checkbox" ${action.enabled!==false?'checked':''}> Enabled</label></div>
<div class="form-group"><label>Action Name</label><input id="aa-label-${index}" value="${f(action.label||'')}"></div>
<div class="form-group"><label>Action Key</label><input id="aa-key-${index}" value="${f(action.key||'')}"><small>Stable internal name, e.g. catering_request or table_reservation.</small></div>
<div class="form-group"><label>What should the AI do?</label><textarea id="aa-desc-${index}">${f(action.description||'')}</textarea></div>
<div class="form-group"><label>Customer details to collect</label><input id="aa-fields-${index}" value="${f(actionFieldsText(action.fields))}" placeholder="customer_name, phone, request"><small>Add or remove fields per client. The AI asks only for missing required details.</small></div>
<div class="form-group"><label><input id="aa-confirm-${index}" type="checkbox" ${action.confirmation_required!==false?'checked':''}> Require customer confirmation before execution</label></div>
<div class="form-group"><label>Where does this action execute?</label><select id="aa-dest-${index}" onchange="renderAgentActionsEditor()">${destinationOptions(destination.type||'unconfigured')}</select></div>
${destination.type==='integration'?`<div class="form-group"><label>Connected Integration</label><select id="aa-integration-${index}">${integrationOptions(destination.integration_id)}</select></div><div class="form-group"><label>Execute Endpoint</label><input id="aa-endpoint-${index}" value="${f(destination.endpoint||((destination.operations||{}).execute||{}).endpoint||'')}" placeholder="/orders or /bookings"><small>For Webhook integrations the configured webhook URL is used. For API/POS/CRM/ERP use a relative endpoint.</small></div>`:''}
<div class="form-group"><label>Availability Source</label><select id="aa-avail-${index}" onchange="renderAgentActionsEditor()">${availabilityOptions(availability.mode||'none')}</select></div>
${availability.mode==='xvond_schedule'?`<div style="padding:10px;border:1px solid #e5e7eb;border-radius:10px"><div class="form-group"><label>Date field</label><input id="aa-date-field-${index}" value="${f(availability.date_field||'date')}"></div><div class="form-group"><label>Time field</label><input id="aa-time-field-${index}" value="${f(availability.time_field||'time')}"></div><div class="form-group"><label>Optional resource field</label><input id="aa-resource-field-${index}" value="${f(availability.resource_field||'')}" placeholder="staff"></div><div class="form-group"><label>Working days</label><div>${weekdayChecks(index,schedule.weekdays)}</div></div><div style="display:grid;grid-template-columns:1fr 1fr 1fr;gap:8px"><div class="form-group"><label>Start</label><input id="aa-start-${index}" type="time" value="${f(schedule.start||'')}"></div><div class="form-group"><label>End</label><input id="aa-end-${index}" type="time" value="${f(schedule.end||'')}"></div><div class="form-group"><label>Slot minutes</label><input id="aa-slot-${index}" type="number" min="5" value="${f(schedule.slot_minutes||30)}"></div></div></div>`:''}
${readinessHtml(action)}</div>`}

function collectCurrentActionEditor(){if(!document.querySelector('[data-aa-card]'))return;const next=[];xvondActionEditor.actions.forEach((old,index)=>{const by=id=>document.getElementById(id);if(!by(`aa-key-${index}`))return;const destType=by(`aa-dest-${index}`).value,availMode=by(`aa-avail-${index}`).value;const destination={type:destType};if(destType==='integration'){destination.integration_id=Number(by(`aa-integration-${index}`)?.value||0)||null;const endpoint=by(`aa-endpoint-${index}`)?.value.trim()||'';destination.operations={execute:{method:'POST',endpoint}}}
const availability={mode:availMode};if(availMode==='xvond_schedule'){availability.date_field=by(`aa-date-field-${index}`).value.trim();availability.time_field=by(`aa-time-field-${index}`).value.trim();availability.resource_field=by(`aa-resource-field-${index}`).value.trim()||null;availability.schedule={weekdays:[...document.querySelectorAll(`.aa-weekday[data-index="${index}"]:checked`)].map(x=>Number(x.value)),start:by(`aa-start-${index}`).value,end:by(`aa-end-${index}`).value,slot_minutes:Number(by(`aa-slot-${index}`).value||30),capacity:1}}
next.push({key:by(`aa-key-${index}`).value.trim(),label:by(`aa-label-${index}`).value.trim(),description:by(`aa-desc-${index}`).value.trim(),enabled:by(`aa-enabled-${index}`).checked,fields:actionFieldsFromText(by(`aa-fields-${index}`).value),confirmation_required:by(`aa-confirm-${index}`).checked,destination,availability})});xvondActionEditor.actions=next}

function renderAgentActionsEditor(){collectCurrentActionEditor();const e=xvondActionEditor;const templateOptions=`<option value="">Choose template</option>`+e.templates.map(t=>`<option value="${f(t.id)}" ${t.id===e.templateId?'selected':''}>${f(t.label)}</option>`).join('');openModal('AI Employee Actions',`<p style="margin-top:0">These are real operations the employee can perform on Website Chat now and on other channels later. Start from a business template, then change anything for this client.</p><div style="display:flex;gap:8px;align-items:end"><div class="form-group" style="flex:1"><label>Business Template</label><select id="aa-template">${templateOptions}</select></div><button class="table-button" onclick="applyAgentActionTemplate()">Apply Template</button><button class="table-button" onclick="addCustomAgentAction()">+ Custom Action</button></div>${e.actions.length?e.actions.map(actionCard).join(''):'<div class="agent-card"><strong>No actions configured.</strong><div class="meta">Apply a template or add a custom action.</div></div>'}<button class="modal-submit" onclick="saveAgentActions()">Save & Validate Actions</button><div style="margin-top:22px;padding-top:16px;border-top:1px solid #e5e7eb"><h3>Real Customer Operations</h3>${e.requests.length?e.requests.map(x=>`<div class="agent-card" style="margin-top:10px"><strong>${f(x.action_type)} #${x.id}</strong><div class="meta">${f(x.status)} · Conversation #${f(x.conversation_id||'—')}</div><div class="meta" style="margin-top:6px">${f(x.summary||'')}</div><div style="margin-top:8px">${requestDetailsHtml(x.details)}</div><div class="agent-actions" style="margin-top:10px">${!['in_progress','processing','completed','cancelled'].includes(x.status)?`<button class="table-button" onclick="setActionRequestStatus(${x.id},'in_progress')">Start</button>`:''}${x.status!=='completed'?`<button class="table-button" onclick="setActionRequestStatus(${x.id},'completed')">Complete</button>`:''}${x.status!=='cancelled'?`<button class="table-button" onclick="setActionRequestStatus(${x.id},'cancelled')">Cancel</button>`:''}</div></div>`).join(''):'<p>No customer operations yet.</p>'}</div>`)}

async function openAgentActions(companyId,agentId){try{const [cfg,templates,integrations,requests]=await Promise.all([api(`/admin/agent-actions/${agentId}`),api('/admin/agent-actions/templates/catalog'),api(`/admin/integrations/companies/${companyId}`),api(`/admin/agent-actions/companies/${companyId}/requests?agent_id=${agentId}`)]);xvondActionEditor={companyId:Number(companyId),agentId:Number(agentId),templateId:cfg.template_id||null,actions:deepClone(cfg.actions||[]),templates:templates.templates||[],integrations:integrations.integrations||[],requests:requests.requests||[]};renderAgentActionsEditor()}catch(e){alert(e.message)}}
function applyAgentActionTemplate(){const id=document.getElementById('aa-template').value,t=xvondActionEditor.templates.find(x=>x.id===id);if(!t)return;xvondActionEditor.templateId=t.id;xvondActionEditor.actions=deepClone(t.actions||[]);renderAgentActionsEditor()}
function addCustomAgentAction(){collectCurrentActionEditor();xvondActionEditor.actions.push({key:`custom_action_${xvondActionEditor.actions.length+1}`,label:'Custom Action',description:'',enabled:true,fields:[{key:'customer_name',label:'Customer name',required:true,type:'text'},{key:'phone',label:'Phone',required:true,type:'text'}],confirmation_required:true,availability:{mode:'none'},destination:{type:'xvond_internal'}});renderAgentActionsEditor()}
function removeAgentAction(index){collectCurrentActionEditor();xvondActionEditor.actions.splice(index,1);renderAgentActionsEditor()}
async function saveAgentActions(){try{collectCurrentActionEditor();const result=await api(`/admin/agent-actions/${xvondActionEditor.agentId}`,{method:'PUT',body:JSON.stringify({template_id:xvondActionEditor.templateId,actions:xvondActionEditor.actions})});xvondActionEditor.actions=deepClone(result.actions||xvondActionEditor.actions);await openAgentActions(xvondActionEditor.companyId,xvondActionEditor.agentId)}catch(e){alert(e.message)}}
async function setActionRequestStatus(id,status){try{await api(`/admin/agent-actions/requests/${id}`,{method:'PATCH',body:JSON.stringify({status})});await openAgentActions(xvondActionEditor.companyId,xvondActionEditor.agentId)}catch(e){alert(e.message)}}
function injectAgentActionButtons(companyId){document.querySelectorAll('.agent-card').forEach(card=>{if(card.querySelector('.xvond-actions-btn'))return;const edit=card.querySelector('button[onclick^="openEditAIEmployee"]');if(!edit)return;const match=(edit.getAttribute('onclick')||'').match(/openEditAIEmployee\((\d+),(\d+)\)/);if(!match)return;const agentId=Number(match[2]),b=document.createElement('button');b.className='table-button xvond-actions-btn';b.textContent='Actions';b.onclick=()=>openAgentActions(Number(companyId),agentId);edit.parentElement.insertBefore(b,edit.nextSibling)})}
if(typeof openSimpleCompany==='function'){const baseOpenSimpleCompany=openSimpleCompany;openSimpleCompany=async function(companyId){const result=await baseOpenSimpleCompany(companyId);injectAgentActionButtons(companyId);return result};window.openCompany=openSimpleCompany}
