async function openHumanConversation(companyId,agentId,conversationId){try{const [thread,sessions]=await Promise.all([api(`/admin/operations/companies/${companyId}/conversations/${conversationId}`),api(`/admin/handoff/companies/${companyId}/sessions`)]);const session=(sessions.sessions||[]).find(x=>+x.conversation_id===+conversationId);const human=session&&session.mode==='human';openModal(`Conversation #${conversationId}`,`<div style="max-height:360px;overflow:auto;margin-bottom:14px">${(thread.messages||[]).map(m=>`<div class="agent-card" style="margin:8px 0"><div class="meta">${m.role==='user'?'Customer':m.role==='human'?'Human':'AI'}</div><div style="white-space:pre-wrap">${f(m.content)}</div></div>`).join('')}</div><div class="agent-actions">${human?`<button class="table-button" onclick="returnConversationToAI(${companyId},${conversationId},${agentId})">Return to AI</button>`:`<button class="table-button" onclick="takeOverConversation(${companyId},${conversationId},${agentId})">Take Over</button>`}</div>${human?`<div class="form-group" style="margin-top:14px"><label>Human Reply</label><textarea id="human-reply-text" placeholder="Write a reply to the customer"></textarea></div><button class="modal-submit" onclick="sendHumanConversationReply(${companyId},${agentId},${conversationId})">Send Reply</button>`:''}`)}catch(e){alert(e.message)}}
async function sendHumanConversationReply(companyId,agentId,conversationId){const el=document.getElementById('human-reply-text'),message=(el.value||'').trim();if(!message)return;try{await api(`/admin/handoff/companies/${companyId}/conversations/${conversationId}/message`,{method:'POST',body:JSON.stringify({message})});await openHumanConversation(companyId,agentId,conversationId)}catch(e){alert(e.message)}}
openHumanTakeover=async function(c,a){try{simpleCompanyId=+c;const r=await api(`/admin/handoff/companies/${c}/sessions`);const sessions=(r.sessions||[]).filter(x=>+x.agent_id===+a);openModal('Conversations',sessions.length?sessions.map(s=>`<div class="agent-card" style="margin-bottom:10px"><strong>${s.channel==='whatsapp'?'WhatsApp':'Website'} · Conversation #${s.conversation_id}</strong><div class="meta">Mode: ${s.mode==='human'?'Human':'AI'}</div>${s.last_message?`<div class="meta">${f(s.last_message)}</div>`:''}${s.handoff_reason?`<div class="meta">Reason: ${f(s.handoff_reason)}</div>`:''}<div class="agent-actions"><button class="table-button" onclick="openHumanConversation(${c},${a},${s.conversation_id})">Open</button>${s.mode==='human'?`<button class="table-button" onclick="returnConversationToAI(${c},${s.conversation_id},${a})">Return to AI</button>`:`<button class="table-button" onclick="takeOverConversation(${c},${s.conversation_id},${a})">Take Over</button>`}</div></div>`).join(''):'<p>No conversations yet.</p>')}catch(e){alert(e.message)}}

if(typeof saveAgentActions==='function'){
  saveAgentActions=async function(){
    try{
      collectCurrentActionEditor();
      const companyId=xvondActionEditor.companyId,agentId=xvondActionEditor.agentId;
      const profile=await api(`/admin/ai-employee-profile/companies/${companyId}/${agentId}`);
      await api(`/admin/agent-actions/${agentId}`,{method:'PUT',body:JSON.stringify({template_id:xvondActionEditor.templateId,actions:xvondActionEditor.actions})});
      await api(`/admin/ai-employee-profile/companies/${companyId}/${agentId}`,{method:'PUT',body:JSON.stringify({name:profile.name,business_name:profile.business_name,business_type:profile.business_type||null,reply_language:profile.reply_language||'auto',conversation_style:profile.conversation_style||'professional_friendly',greeting:profile.greeting||null,instructions:profile.instructions||null})});
      await openAgentActions(companyId,agentId);
    }catch(e){alert(e.message)}
  };
}
