let simpleCompanyId=null;
function simpleEscape(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}
function f(v){return simpleEscape(v||"")}
function businessTypeOptions(selected=""){const types=["Salon / Beauty","Restaurant / Cafe","Retail Store","E-commerce","Clinic / Medical Center","Dental Clinic","Pharmacy","Real Estate","Hotel / Hospitality","Travel / Tourism","Professional Services","Education / Training","Gym / Fitness","Automotive","Home Services","Maintenance / Contracting","Logistics / Delivery","Technology / Software","Marketing / Media","Financial / Accounting Services","Legal Services","Other"];return `<option value="">Select business type</option>`+types.map(t=>`<option value="${f(t)}" ${t===selected?"selected":""}>${f(t)}</option>`).join("")}

// Shared helpers retained for the current Company Control Center.
// Company rendering and AI Employee profile forms live in company-control-center.js
// and employee-capabilities.js. Do not reintroduce company facts or fixed booking/order
// switches into the employee profile here.

async function setSimpleChannelStatus(c,id,en){try{await api(`/admin/channels/${id}`,{method:"PUT",body:JSON.stringify({enabled:en})});await openSimpleCompany(c)}catch(e){alert(e.message)}}

async function takeOverConversation(c,conversationId,a){try{await api(`/admin/handoff/companies/${c}/conversations/${conversationId}/take-over`,{method:"POST"});await openHumanTakeover(c,a)}catch(e){alert(e.message)}}
async function returnConversationToAI(c,conversationId,a){try{await api(`/admin/handoff/companies/${c}/conversations/${conversationId}/return-ai`,{method:"POST"});await openHumanTakeover(c,a)}catch(e){alert(e.message)}}

function openPDFKnowledge(c,a){simpleCompanyId=+c;openModal("Add PDF Knowledge",`<p>Upload a menu, price list, services catalog, scanned PDF or company document.</p><div class="form-group"><label>PDF File</label><input id="simple-pdf-file" type="file" accept="application/pdf,.pdf"></div><button class="modal-submit" onclick="uploadPDFKnowledge(${a})">Upload & Learn</button>`)}
async function uploadPDFKnowledge(a){const input=document.getElementById("simple-pdf-file"),file=input.files&&input.files[0];if(!file){alert("Choose a PDF file first.");return}const fd=new FormData();fd.append("file",file);try{const token=localStorage.getItem("xvond_admin_token")||localStorage.getItem("token");const res=await fetch(`/admin/ai-employees/companies/${simpleCompanyId}/${a}/knowledge/pdf`,{method:"POST",headers:token?{Authorization:`Bearer ${token}`}:{},body:fd});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.detail||"PDF upload failed");await openKnowledgeManager(simpleCompanyId,a)}catch(e){alert(e.message)}}

function openWhatsAppSetup(a,c){openModal("WhatsApp Connection",`<div class="modal-intro"><strong>Meta WhatsApp Business</strong><p>Save the real Meta credentials first. Activation remains a separate readiness-gated step.</p></div><div class="form-group"><label>Phone Number ID</label><input id="simple-wa-phone-id"></div><div class="form-group"><label>Access Token</label><input id="simple-wa-access-token" type="password"></div><div class="form-group"><label>Verify Token</label><input id="simple-wa-verify-token" type="password"></div><div class="form-group"><label>App Secret</label><input id="simple-wa-app-secret" type="password"></div><div class="form-group"><label>Graph API Version</label><input id="simple-wa-version" value="v23.0"></div><button class="modal-submit" onclick="saveSimpleWhatsApp(${c})">Save WhatsApp Connection</button>`)}
async function saveSimpleWhatsApp(c){try{const result=await api(`/admin/channels/${c}/whatsapp-config`,{method:"PUT",body:JSON.stringify({phone_number_id:document.getElementById("simple-wa-phone-id").value,access_token:document.getElementById("simple-wa-access-token").value,verify_token:document.getElementById("simple-wa-verify-token").value,app_secret:document.getElementById("simple-wa-app-secret").value,graph_api_version:document.getElementById("simple-wa-version").value})});closeModal();await openSimpleCompany(simpleCompanyId);if(result&&!result.ready&&result.blockers?.length)alert("WhatsApp saved. Before activation: "+result.blockers.join("; "))}catch(e){alert(e.message)}}
